import "../styles/global.css";
import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import Navbar from "../components/organism/Navbar";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* <p className="bg-yellow-300">hello world</p> */}
      </body>
    </html>
  );
}
