import "@src/styles/global.css";
import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import Navbar from "../components/components/Navbar";
import { cn } from "@src/lib/utils";
import "material-symbols";
import Footer from "../components/components/Footer";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <Navbar />
        <main className="mb-6 flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
